[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/xeipuuv/gojsonschema"
  version = "1.1.0"

[prune]
  go-tests = true
  unused-packages = true
