/*
 * Semtech Localization Algorithms
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type GatewayReceptionRssi struct {

	GatewayId string `json:"gatewayId"`

	AntennaId int32 `json:"antennaId"`

	Rssi float64 `json:"rssi"`

	Snr float64 `json:"snr"`

	AntennaLocation *AntennaLocation `json:"antennaLocation,omitempty"`
}
