/*
 * Semtech Localization Algorithms
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LocalizationResponse struct {

	Result *LocationEstimate `json:"result,omitempty"`

	Warnings []string `json:"warnings,omitempty"`

	Errors []string `json:"errors,omitempty"`

	CorrelationId string `json:"correlationId,omitempty"`
}
