/*
 * Semtech Localization Algorithms
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type AntennaLocation struct {

	Latitude float64 `json:"latitude"`

	Longitude float64 `json:"longitude"`

	Altitude float64 `json:"altitude"`
}
