/*
 * Semtech Localization Algorithms
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/semtech-localization-algorithms/v1/",
		Index,
	},

	Route{
		"59f34d6667ba551494199971",
		strings.ToUpper("Post"),
		"/semtech-localization-algorithms/v1/rssi",
		59f34d6667ba551494199971,
	},

	Route{
		"59f34d6667ba551494199974",
		strings.ToUpper("Post"),
		"/semtech-localization-algorithms/v1/tdoa",
		59f34d6667ba551494199974,
	},

	Route{
		"5a1c1701a5840134eb76ce9b",
		strings.ToUpper("Post"),
		"/semtech-localization-algorithms/v1/rssiMultiframe",
		5a1c1701a5840134eb76ce9b,
	},

	Route{
		"5a1c19f4c2a18ab275ac584d",
		strings.ToUpper("Post"),
		"/semtech-localization-algorithms/v1/tdoaMultiframe",
		5a1c19f4c2a18ab275ac584d,
	},
}
